### PR TITLE
[WIP] JSRS Audio Changes

### PR DESCRIPTION
**Pull request by DarkMessiah27**
**When merged this pull request will:**
- Removes FOW and IFA weapon soundset changes. This will allow the JSRS FOW and IFA compat mods to then do their thing.
- Adds IFA JSRS soundsets from the JSRS IFA compat mod to the CSA and LEN weapons.

### CODE REVIEW

**Comment by FakeMessiah27** [comment]
Okay, clearly we've been on different wavelengths here. 

You're saying the only weapon classes that should continue to exist in any of the JSRS audio expansion files, are classes that have sound changes made to them. And inside those weapon classes, the only sub classes that should remain are fire mode classes such as "FullAuto" or "Single" and inside _those_ classes, only sound related entries should remain.

Correct?

As for the ammo classes, I wasn't aware those needed changing. An example of how or where to add sound entries to the classes in those files would be nice.

**Comment by Drofseh** [comment]
Yah that sounds broadly correct. But you need make sure to keep and parent class, even if it doesn't have changes.
For example:

```
class fow_rifleBolt_base;

class fow_w_leeenfield_no4mk1 : fow_rifleBolt_base {
    class Single : Mode_SemiAuto {
        class StandardSound : BaseSoundModeType {
            soundSetShot[] = {"jsrs_leeenfield_shot_soundset","jsrs_ww2_bolt_rifle_reverb_soundset"};
        };
    };
};
```

For the ammo example, look at the config I sent you on discord

**Comment by FakeMessiah27** [comment]
Alright, I'll get on it.

**Comment by Drofseh** [comment]
Refactoring whole mod so this is obsolete

**Pull request closed without merging**
